# Lab 2 Session

## Dataset loading and preprocessing 

In [1]:
f=open('Dataset/sentiment.txt','r')
sentences=f.readlines()
f.close()

In [2]:
import re

stopwords = ["a", "about", "above", "above", "across", "after", "afterwards", "again", "against", "all", "almost", "alone", "along", "already", "also","although","always","am","among", "amongst", "amoungst", "amount",  "an", "and", "another", "any","anyhow","anyone","anything","anyway", "anywhere", "are", "around", "as",  "at", "back","be","became", "because","become","becomes", "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", "both", "bottom","but", "by", "call", "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", "de", "describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", "either", "eleven","else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything", "everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former", "formerly", "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own","part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "thereupon", "these", "they", "thickv", "thin", "third", "this", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards", "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your", "yours", "yourself", "yourselves", "the"]

def text_cleaner(text): 
    text=remove_link(text.lower())
    long_words=[]
    for i in text.split():
        if i not in stopwords:                  
            long_words.append(i)
    return long_words

def remove_link(text):
    regex = r'https?://[^\s<>)"‘’]+'
    match = re.sub(regex,' ', text)
    regex = r'https?:|urls?|[/\:,-."\'?!;…]+'
    tweet = re.sub(regex,' ', match)
    tweet = re.sub("[^a-zA-Z_]", " ", tweet)
    tweet = re.sub("[ ]+", " ", tweet) 
    return tweet


In [3]:
vocabulary=[]
X=[]
y=[]
for line in sentences:
	texts=line.strip().lower().split('\t')
	tokens=text_cleaner(texts[0])
	y.append(texts[1])
	X.append(tokens)
	for word in tokens:
		vocabulary.append(word)

## Conversion of text to vector space

In [4]:
def t2v(tokens,vocabulary):
	vect=[]
	for feature in vocabulary:
		if feature in tokens:
			vect.append(1)
		else:
			vect.append(0)
	return vect

In [5]:
vector=[]
for tokens in X:
	vect=t2v(tokens,vocabulary)
	vector.append(vect)

In [6]:
import numpy as np
vector=np.asarray(vector)
y=np.asarray(y)
print("Number of samples,Number of features")
vector.shape 


Number of samples,Number of features


(1143, 12213)

# Feature selection

### Mutual Information based feature selection

In [7]:
from sklearn.feature_selection import mutual_info_classif
X_new = mutual_info_classif(vector,y)
X_new.shape

(12213,)

In [8]:
N=len(vocabulary)
avg=0
for mi in X_new:
    avg+=mi
avg=avg/N
feat_selection=[]
for i,mi in enumerate(X_new):
    if mi>avg:
        feat_selection.append(vocabulary[i])
len(feat_selection)

4333

In [9]:
feat_selection

['humbles',
 'exalted',
 'semst',
 'sought',
 'truth',
 'stand',
 'world',
 'tight',
 'hug',
 'relieve',
 'morality',
 'hitch',
 'semst',
 'godly',
 'trusts',
 'wants',
 'god',
 'day',
 'wisdom',
 'sense',
 'semst',
 'days',
 'freethinker',
 'v',
 'deen',
 'instead',
 'strongly',
 'faith',
 'martin',
 'semst',
 'fears',
 'god',
 'god',
 'semst',
 'pray',
 'catholic',
 'semst',
 'life',
 'faith',
 'inevitable',
 'henri',
 'semst',
 'semst',
 'i',
 'semst',
 'father',
 'vessel',
 'ur',
 'sundaymorningshow',
 'semst',
 'remember',
 'prayed',
 'god',
 'god',
 'strong',
 'thank',
 'god',
 'god',
 'jesus',
 'religious',
 'environment',
 'create',
 'royal',
 'environment',
 'thank',
 'god',
 'sanctify',
 'word',
 'truth',
 'john',
 'semst',
 'psalm',
 'sign',
 'humanist',
 'cloth',
 'tcot',
 'stay',
 'love',
 'tcot',
 'semst',
 'pray',
 'won',
 'sees',
 'difficulties',
 'counts',
 'god',
 'semst',
 'beast',
 'school',
 'secular',
 'secularism',
 'courts',
 'jesus',
 'believe',
 'died',
 'conf

In [10]:
vector_feat=[]
for tokens in X:
	vect=t2v(tokens,feat_selection)
	vector_feat.append(vect)

In [11]:
import numpy as np
vector_feat=np.asarray(vector_feat)
vector_feat.shape

(1143, 4333)

In [12]:
test_ip="I love watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_pos=t2v(tokens,feat_selection)
tokens

['i', 'love', 'watching', 'netflix', 'original', 'movies']

In [13]:
test_ip="I hate watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_neg=t2v(tokens,feat_selection)
tokens

['i', 'hate', 'watching', 'netflix', 'original', 'movies']

In [14]:
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [15]:
svml=svm.LinearSVC()
model = svml.fit(vector_feat,y)

/home/gyanendro/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [16]:
res = model.predict([vect_pos])
res

array(['1'], dtype='<U1')

In [17]:
res = model.predict([vect_neg])
res

array(['0'], dtype='<U1')

### L1-based feature selection

In [18]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(vector, y)
t_model = SelectFromModel(lsvc, prefit=True)
X_new = t_model.transform(vector)
X_new.shape

(1143, 9)

In [19]:
X_new[1]

array([0, 0, 0, 1, 0, 1, 0, 1, 1])

In [20]:
svml=svm.LinearSVC()
model = svml.fit(X_new,y)

In [21]:
test_ip="I love watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_pos=t2v(tokens,vocabulary)
vect_pos = t_model.transform(np.asarray([vect_pos]))
vect_pos

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
res = model.predict(vect_pos)
res

array(['0'], dtype='<U1')

In [23]:
test_ip="I hate watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_neg=t2v(tokens,vocabulary)
vect_neg = t_model.transform(np.asarray([vect_neg]))
vect_neg

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
res = model.predict(vect_neg)
res

array(['0'], dtype='<U1')

# Dimensional Reduction

### PCA based dimensional reduction

In [25]:
from sklearn.decomposition import PCA
pca = PCA(n_components=200)
X_new=pca.fit_transform(vector)
X_new.shape

(1143, 200)

In [26]:
svml=svm.LinearSVC()
model = svml.fit(X_new,y)

/home/gyanendro/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [27]:
test_ip="I love watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_pos=t2v(tokens,vocabulary)
vect_pos = pca.transform(np.asarray([vect_pos]))
vect_pos.shape

(1, 200)

In [28]:
res = model.predict(vect_pos)
res

array(['1'], dtype='<U1')

In [29]:
test_ip="I hate watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_neg=t2v(tokens,vocabulary)
vect_neg = pca.transform(np.asarray([vect_neg]))
vect_neg.shape

(1, 200)

In [30]:
res = model.predict(vect_neg)
res

array(['0'], dtype='<U1')

### SVD based dimensional reduction

In [31]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=200, n_iter=7, random_state=42)
X_new=svd.fit_transform(vector)
X_new.shape

(1143, 200)

In [32]:
svml=svm.LinearSVC()
model = svml.fit(X_new,y)

/home/gyanendro/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [33]:
test_ip="I love watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_pos=t2v(tokens,vocabulary)
vect_pos = svd.transform(np.asarray([vect_pos]))
vect_pos.shape

(1, 200)

In [34]:
test_ip="I hate watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_neg=t2v(tokens,vocabulary)
vect_neg = svd.transform(np.asarray([vect_neg]))
vect_neg.shape

(1, 200)

In [35]:
res = model.predict(vect_pos)
res

array(['1'], dtype='<U1')

In [36]:
res = model.predict(vect_neg)
res

array(['1'], dtype='<U1')