# Lab Session 1: Machine Learning

### Define a task for classification

# Load the dataset and Preprocess

In [1]:
f=open('sentiment.txt','r')
sentences=f.readlines()
f.close()

In [2]:
print(sentences[0])

He who exalts himself shall      be humbled; and he who humbles himself shall be exalted.Matt 23:12.     #SemST	1



# Feature Extraction
Features can be list Unigrams or bigrams or trigrams ....  or combine

We are considering unigram

In [3]:
import re
import numpy as np

stopwords = ["a", "about", "above", "above", "across", "after", "afterwards", "again", "against", "all", "almost", "alone", "along", "already", "also","although","always","am","among", "amongst", "amoungst", "amount",  "an", "and", "another", "any","anyhow","anyone","anything","anyway", "anywhere", "are", "around", "as",  "at", "back","be","became", "because","become","becomes", "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", "both", "bottom","but", "by", "call", "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", "de", "describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", "either", "eleven","else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything", "everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former", "formerly", "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own","part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "thereupon", "these", "they", "thickv", "thin", "third", "this", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards", "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your", "yours", "yourself", "yourselves", "the"]

def text_cleaner(text): 
    text=remove_link(text.lower())
    long_words=[]
    for i in text.split():
        if i not in stopwords:                  
            long_words.append(i)
    return long_words

def remove_link(text):
    regex = r'https?://[^\s<>)"‘’]+'
    match = re.sub(regex,' ', text)
    regex = r'https?:|urls?|[/\:,-."\'?!;…]+'
    tweet = re.sub(regex,' ', match)
    tweet = re.sub("[^a-zA-Z_]", " ", tweet)
    tweet = re.sub("[ ]+", " ", tweet) 
    return tweet

In [36]:
vocabulary=[]     # Features                  
samples=[]        # List of samples
y=[]              # Class Label
for line in sentences:
	texts=line.strip().lower().split('\t')
	tokens=text_cleaner(texts[0])
	y.append(int(texts[1]))
	samples.append(tokens)
	for word in tokens:
		vocabulary.append(word)

In [5]:
print("Number of features is :"+str(len(vocabulary)))

Number of features is :12213


# Represent samples using vector space model

Each sample will look like
 
    f1, f2, f3,      fk
1. [w11, w12, w13m ....., w1k] c1
2. [w21, w22, w23m ....., w2k] c2
....

In this example, we have considered boolean vector space model

In [6]:
def t2v(tokens,attributes):
    vect=[]
    for feature in attributes:
        if feature in tokens:
            vect.append(1)         #Presence
        else:
            vect.append(0)         #Absence
    return vect

In [37]:
vector=[]
for i,tokens in enumerate(samples):
    vect=t2v(tokens,vocabulary)
    vector.append((vect,y[i],i)) #vector representation, label, sentence no.
    
i=2
print("Sentence No. \t Vector Representation \t label")
print(str(vector[i][2])+" "+str(vector[i][0])+" "+str(vector[i][1]))

Sentence No. 	 Vector Representation 	 label
2 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0

# Splitting the dataset for training and testing

In [8]:
import random
random.shuffle(vector)

X=[]
y=[]
s_idx=[]
for i in vector:
    X.append(i[0]) #vector representation
    y.append(i[1]) #label
    s_idx.append(i[2]) #sentence_number
X=np.asarray(X)
y=np.asarray(y)
s_idx=np.asarray(s_idx)
print("Number of samples and number of Features")
X.shape

Number of samples and number of Features


(1143, 12213)

In [9]:
del vector,samples

import gc
gc.collect()

40

In [10]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=10)
folds=[]
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]   #sentence vector
    y_train, y_test = y[train_index], y[test_index]   #label
    s_train, s_test = s_idx[train_index], s_idx[test_index]   #sentence index
    folds.append((X_train, X_test, y_train, y_test,s_train, s_test))

TRAIN: [ 115  116  117 ... 1140 1141 1142] TEST: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114]
TRAIN: [   0    1    2 ... 1140 1141 1142] TEST: [115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132
 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204
 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 

## 1st fold

In [11]:
(X_train, X_test, y_train, y_test,s_train, s_test)=folds[0]
print("Number of training samples :"+str(len(X_train)))
print("number of test data :"+str(len(X_test)))

Number of training samples :1029
number of test data :114


## Building a classifier

In [12]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import NearestCentroid
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression

# Naive bayes Classifier with Multinomial Kernal

In [13]:
mnb=MultinomialNB()
model = mnb.fit(X_train,y_train)

y = model.predict(X_test)
i=0
print("Input Data => Predicted => Actual")
for p in y:
    print(X_test[i]," =>" , p," =>"  ,y_test[i])
    i+=1

Input Data => Predicted => Actual
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 1  => 1
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 1  => 1
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 0  => 1
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 0  => 1
[0 0 0 ... 0 0 1]  => 1  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 1  => 1
[0 0 0 ... 0 0 1]  => 0  => 1
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 0  => 0
[0 0 0 ... 0 0 1]  => 1  => 1
[0 0 0

In [51]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [38]:
print(y_test)
pred0=[]
true0=[]
pred1=[]
true1=[]

for i,ii in enumerate(y_test):
    if ii==1:
        true1.append(ii)
        pred1.append(y[i])
    else:
        true0.append(ii)
        pred0.append(y[i])

pred=pred0+pred1
true=true0+true1
print(true)
del true0,true1,pred0,pred1

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0
 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1
 1 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 1 1 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [56]:
print("Accuracy ",accuracy_score(y_test, y, normalize = True))
print("Precision ",precision_score(y_test, y, average = None))
print("Recall ",recall_score(y_test, y, average = None))
print("F1 Score ",f1_score(y_test, y, average = None))
print("AUC Score ", roc_auc_score(true, pred))

Accuracy  0.5964912280701754
Precision  [0.68131868 0.26086957]
Recall  [0.78481013 0.17142857]
F1 Score  [0.72941176 0.20689655]
AUC Score  0.5


In [40]:
test_ip="I love watching netflix original movies"
tokens=text_cleaner(test_ip)
vect_pos=t2v(tokens,vocabulary)

test_ip="I hate watching netflix original movies" #You have won 1 crore rupees #India ka dusra nam he Bharat
tokens=text_cleaner(test_ip)
vect_neg=t2v(tokens,vocabulary)

In [41]:
y = model.predict([vect_pos,vect_neg])
y

array([0.46823194, 0.40087682])

# Naive Bayes with Gaussian kernal

In [21]:
gnb= GaussianNB()
model = gnb.fit(X_train,y_train)

y = model.predict(X_test)

print("Accuracy ",accuracy_score(y_test, y, normalize = True))

Accuracy  0.6929824561403509


In [22]:
cc=NearestCentroid()
model = cc.fit(X_train,y_train)

y = model.predict(X_test)

print("Accuracy ",accuracy_score(y_test, y, normalize = True))

Accuracy  0.5964912280701754


In [23]:
dtc =DecisionTreeClassifier()
model = dtc.fit(X_train,y_train)

y = model.predict(X_test)

print("Accuracy ",accuracy_score(y_test, y, normalize = True))

Accuracy  0.7807017543859649


In [24]:
knnc=KNeighborsClassifier(n_neighbors=15)
model = knnc.fit(X_train,y_train)

y = model.predict(X_test)

print("Accuracy ",accuracy_score(y_test, y, normalize = True))

Accuracy  0.6666666666666666


In [25]:
svml=svm.LinearSVC()
model = svml.fit(X_train,y_train)

y = model.predict(X_test)

print("Accuracy ",accuracy_score(y_test, y, normalize = True))

Accuracy  0.7192982456140351


/home/gyanendro/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [26]:
clf = MLPClassifier(solver='sgd', hidden_layer_sizes=(10,), activation="relu")
model = clf.fit(X_train,y_train)

y = model.predict(X_test)

print("Accuracy ",accuracy_score(y_test, y, normalize = True))

Accuracy  0.7456140350877193


/home/gyanendro/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [27]:
cLR = LogisticRegression()
model = cLR.fit(X_train,y_train)

y = model.predict(X_test)

print("Accuracy ",accuracy_score(y_test, y, normalize = True))

/home/gyanendro/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy  0.7456140350877193


In [28]:
clf = RandomForestClassifier()
model = clf.fit(X_train,y_train)

y = model.predict(X_test)

print("Accuracy ",accuracy_score(y_test, y, normalize = True))

/home/gyanendro/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Accuracy  0.7807017543859649


In [29]:
cLR = LinearRegression()
model = cLR.fit(X_train,y_train)

y = model.predict(X_test)

for i,p in enumerate(y):
    print(p, y_test[i])




-0.2244230773660928 0
-0.007615314731507783 0
0.34820374124438963 0
0.4852132244555255 0
-0.19781480415983033 0
0.6803229111950092 0
0.7743867272521321 0
0.5222345866475585 0
0.8749057731552663 1
-0.6582680580542807 0
0.7331631022740683 0
-0.5785082173597881 0
0.42402250628206306 0
0.7189600591648508 0
0.1261771487213773 0
0.9026664516828599 0
0.8457085941111542 1
0.6451274469944761 0
-0.18800626416692157 0
-0.060026982652647054 0
0.25908512924770893 0
0.44878161260429156 1
-0.34966376586329195 0
-0.6029556248296273 1
0.05016847540145697 0
0.24339099165636668 0
0.0432923816774583 0
1.0185413875400218 1
-0.08175502534791901 1
0.6024319376902423 0
0.10438941662930279 0
0.3132878648947468 1
0.006607903429898365 0
0.777549326765007 1
0.7628817014642844 1
0.1949075497101129 0
1.0835047371804478 0
1.5971362604511166 1
-0.11817122137915581 0
0.40930133163268884 1
0.24697847522481237 1
0.7523965981051105 1
-0.09792900728845777 0
0.16603559179139546 1
0.9173354522664097 0
0.3897661095205584 1
0

In [44]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, random_state=0).fit(X_train)
kmeans.labels_

array([0, 0, 0, ..., 1, 0, 0], dtype=int32)

In [45]:
y=kmeans.predict(X_test)

In [46]:
kmeans.predict([vect_neg])

array([1], dtype=int32)

In [47]:
i=0
test_ip=sentences[s_idx[i]].strip().split('\t')[0]
tokens=text_cleaner(test_ip)
vect_sem16=t2v(tokens,vocabulary)
kmeans.predict([vect_sem16])

array([0], dtype=int32)

In [49]:
from sklearn.metrics.cluster import adjusted_rand_score, homogeneity_score, completeness_score, v_measure_score

In [50]:
print("Rand Index score ",adjusted_rand_score(y_test, y))
print("Homogeneity score ",homogeneity_score(y_test, y))
print("Completeness score ",completeness_score(y_test, y))
print("V measure score ",v_measure_score(y_test, y))

Rand Index score  -0.02187857956405962
Homogeneity score  0.002099100180995959
Completeness score  0.002574457652749929
V measure score  0.002312604108943883
